let g:html_indent_tags .= '\|li'
let g:html_indent_tags .= '\|section'
let g:html_indent_tags .= '\|accordian'
let g:html_indent_tags .= '\|accordian-heading'
let g:html_indent_tags .= '\|accordian-body'
